

env:
  global:
    - DISPLAY=""

language: python

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36

install:
  - pip install -r requirements.txt
  - pip install tox

script: pytest

notifications:
  email: false
